<?php

namespace AppBundle\Repository;

use Symfony\Component\Cache\Simple\FilesystemCache;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInfoBasic()
    {
        $cache = new FilesystemCache();
        $cache->delete('findProducts');
        if (!$cache->has('findProducts')) {
            $em = $this->getEntityManager();
            $consult = $em->createQuery('SELECT ' .
                'p.id, p.name, p.price ' .
                'FROM AppBundle:Product p');
            $cache->set('findProducts', $consult->getResult(), 3600);
        }
        return $cache->get('findProducts');

    }
}
